#!/bin/sh
# Provision the test SSH server users and keys, then exec sshd.
#
# Users:
#   master / masterpass  -> passwordless sudo (NOPASSWD) so it can run commands as root
#   guest  / guestpass   -> limited account, no sudo
#
# Test SSH keys are read from the mounted /keys directory (generated on the host
# by `make sshserver-keys`), so the same keypair can be used by the test client.
set -e

MASTER_USER="master"
MASTER_PASS="masterpass"
GUEST_USER="guest"
GUEST_PASS="guestpass"

# create_user <name> <home> <shell> [password]
# Alpine ships a built-in "guest" account (home=/dev/null, shell=/sbin/nologin),
# which collides with our test user. Reliably (re)create a user with an explicit
# home and shell: delete any existing account first, then add it fresh.
create_user() {
    name="$1"
    home="$2"
    shell="$3"
    pass="$4"

    if id "${name}" >/dev/null 2>&1; then
        deluser "${name}" 2>/dev/null || true
        rm -rf "${home}"
    fi
    adduser -D -h "${home}" -s "${shell}" "${name}"
    echo "${name}:${pass}" | chpasswd
}

# --- master: passwordless sudo ----------------------------------------------
create_user "${MASTER_USER}" "/home/${MASTER_USER}" /bin/bash "${MASTER_PASS}"

mkdir -p /etc/sudoers.d
echo "${MASTER_USER} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/90-${MASTER_USER}
chmod 0440 /etc/sudoers.d/90-${MASTER_USER}

# --- guest: limited, no sudo ------------------------------------------------
create_user "${GUEST_USER}" "/home/${GUEST_USER}" /bin/sh "${GUEST_PASS}"

# Deny all sudo explicitly, even if a broad rule exists.
echo "${GUEST_USER} ALL=(ALL) !ALL" > /etc/sudoers.d/91-${GUEST_USER}
chmod 0440 /etc/sudoers.d/91-${GUEST_USER}

# --- SSH keys for key-based auth ---------------------------------------------
# The public key is always provided by the host at /keys/authorized_keys.test.pub
# (generated by `make sshserver-keys`), mounted read-only. The matching private
# key stays on the host so tests can authenticate with it. If the key is missing
# we skip key auth and fall back to password auth rather than failing the boot.
KEYDIR="/keys"

if [ -f "${KEYDIR}/authorized_keys.test.pub" ]; then
    keypub="${KEYDIR}/authorized_keys.test.pub"
else
    echo "sshtest: ${KEYDIR}/authorized_keys.test.pub not found — run 'make sshserver-keys'; key auth disabled" >&2
    keypub=""
fi

install_key() {
    user="$1"
    if [ -z "${keypub}" ] || [ ! -f "${keypub}" ]; then
        echo "sshtest: no authorized key available, skipping key auth for ${user}" >&2
        return 0
    fi
    home="$(getent passwd "$user" | cut -d: -f6)"
    mkdir -p "${home}/.ssh"
    cp "${keypub}" "${home}/.ssh/authorized_keys"
    chown -R "${user}:${user}" "${home}/.ssh"
    chmod 700 "${home}/.ssh"
    chmod 600 "${home}/.ssh/authorized_keys"
}

install_key "${MASTER_USER}"
install_key "${GUEST_USER}"

echo "sshtest: master and guest users provisioned, starting sshd..." >&2
exec "$@"
