//go:build integration

// Package integration contains tests that run against a real SSH server.
//
// Start the test server first (or use `make test-integration`, which does it
// for you):
//
//	make sshserver-up
//	CONDUIT_SSH_TEST_ADDR=127.0.0.1:2222 go test -tags integration ./test/integration/
//
// See test/sshserver/README.md for the server's users and credentials.
package integration

import (
	"net"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"github.com/stretchr/testify/require"
	gossh "golang.org/x/crypto/ssh"
)

const (
	defaultAddr = "127.0.0.1:2222"

	masterUser = "master"
	masterPass = "masterpass"
	guestUser  = "guest"
	guestPass  = "guestpass"
)

func testAddr() string {
	if addr := os.Getenv("CONDUIT_SSH_TEST_ADDR"); addr != "" {
		return addr
	}
	return defaultAddr
}

// testKeyPath returns the path to the private key generated by `make sshserver-keys`
// and mounted into the container as the authorized key.
func testKeyPath() string {
	if p := os.Getenv("CONDUIT_SSH_TEST_KEY"); p != "" {
		return p
	}
	// Fallback: resolve test/sshserver/keys/... relative to this source file so it
	// works regardless of the working directory `go test` uses.
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "test/sshserver/keys/authorized_keys.test"
	}
	return filepath.Join(filepath.Dir(file), "..", "sshserver", "keys", "authorized_keys.test")
}

// requireSSHServer skips the test if the test SSH server is not reachable.
func requireSSHServer(t *testing.T) {
	t.Helper()
	addr := testAddr()
	conn, err := net.DialTimeout("tcp", addr, 2*time.Second)
	if err != nil {
		t.Skipf("test SSH server not reachable at %s (run `make sshserver-up`): %v", addr, err)
	}
	_ = conn.Close()
}

// dial connects to the test SSH server with the given credentials.
func dial(t *testing.T, user, pass string) *gossh.Client {
	t.Helper()
	cfg := &gossh.ClientConfig{
		User:            user,
		Auth:            []gossh.AuthMethod{gossh.Password(pass)},
		HostKeyCallback: gossh.InsecureIgnoreHostKey(), //nolint:gosec // test server
		Timeout:         5 * time.Second,
	}
	client, err := gossh.Dial("tcp", testAddr(), cfg)
	require.NoError(t, err, "dial %s@%s", user, testAddr())
	return client
}

// dialWithKey connects using the host-generated private key as the sole auth method.
func dialWithKey(t *testing.T, user string) *gossh.Client {
	t.Helper()
	keyBytes, err := os.ReadFile(testKeyPath())
	require.NoError(t, err, "read test key %s (run `make sshserver-keys`)", testKeyPath())

	signer, err := gossh.ParsePrivateKey(keyBytes)
	require.NoError(t, err, "parse test key")

	cfg := &gossh.ClientConfig{
		User:            user,
		Auth:            []gossh.AuthMethod{gossh.PublicKeys(signer)},
		HostKeyCallback: gossh.InsecureIgnoreHostKey(), //nolint:gosec // test server
		Timeout:         5 * time.Second,
	}
	client, err := gossh.Dial("tcp", testAddr(), cfg)
	require.NoError(t, err, "dial %s@%s with key", user, testAddr())
	return client
}

// runCmd runs a single command over an SSH session and returns combined output.
func runCmd(t *testing.T, client *gossh.Client, cmd string) (string, error) {
	t.Helper()
	sess, err := client.NewSession()
	require.NoError(t, err)
	defer func() { _ = sess.Close() }()

	out, err := sess.CombinedOutput(cmd)
	return string(out), err
}

func TestMasterCanSudo(t *testing.T) {
	requireSSHServer(t)

	client := dial(t, masterUser, masterPass)
	defer func() { _ = client.Close() }()

	// master has NOPASSWD sudo, so `sudo id` must succeed and report uid=0.
	out, err := runCmd(t, client, "sudo id")
	require.NoError(t, err, "sudo id: %s", out)
	require.Contains(t, out, "uid=0(root)", "master should be able to run as root via sudo")
}

func TestGuestCannotSudo(t *testing.T) {
	requireSSHServer(t)

	client := dial(t, guestUser, guestPass)
	defer func() { _ = client.Close() }()

	// guest is denied sudo; the command must fail and not report uid=0.
	out, err := runCmd(t, client, "sudo -n id")
	require.Error(t, err, "guest must not be able to sudo")
	require.NotContains(t, out, "uid=0(root)", "guest must never run as root")
}

func TestGuestIdentity(t *testing.T) {
	requireSSHServer(t)

	client := dial(t, guestUser, guestPass)
	defer func() { _ = client.Close() }()

	out, err := runCmd(t, client, "id -un")
	require.NoError(t, err, "id -un: %s", out)
	require.Equal(t, guestUser, trim(string(out)))
}

func TestMasterIdentity(t *testing.T) {
	requireSSHServer(t)

	client := dial(t, masterUser, masterPass)
	defer func() { _ = client.Close() }()

	out, err := runCmd(t, client, "id -un")
	require.NoError(t, err, "id -un: %s", out)
	require.Equal(t, masterUser, trim(string(out)))
}

func TestWrongPasswordRejected(t *testing.T) {
	requireSSHServer(t)

	cfg := &gossh.ClientConfig{
		User:            guestUser,
		Auth:            []gossh.AuthMethod{gossh.Password("wrong-password")},
		HostKeyCallback: gossh.InsecureIgnoreHostKey(), //nolint:gosec // test server
		Timeout:         5 * time.Second,
	}
	_, err := gossh.Dial("tcp", testAddr(), cfg)
	require.Error(t, err, "auth with a wrong password must fail")
}

func TestKeyAuthMaster(t *testing.T) {
	requireSSHServer(t)

	client := dialWithKey(t, masterUser)
	defer func() { _ = client.Close() }()

	out, err := runCmd(t, client, "id -un")
	require.NoError(t, err, "id -un: %s", out)
	require.Equal(t, masterUser, trim(string(out)))
}

func TestKeyAuthGuest(t *testing.T) {
	requireSSHServer(t)

	client := dialWithKey(t, guestUser)
	defer func() { _ = client.Close() }()

	out, err := runCmd(t, client, "id -un")
	require.NoError(t, err, "id -un: %s", out)
	require.Equal(t, guestUser, trim(string(out)))
}

func trim(s string) string {
	start, end := 0, len(s)
	for start < end && (s[start] == '\n' || s[start] == '\r' || s[start] == ' ' || s[start] == '\t') {
		start++
	}
	for end > start && (s[end-1] == '\n' || s[end-1] == '\r' || s[end-1] == ' ' || s[end-1] == '\t') {
		end--
	}
	return s[start:end]
}
